import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import Loading from "../components/Loading";
import { WishlistProvider } from "./context/WishlistContext";
import { CartProvider } from "./context/CartListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-com.com.next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "light" }}>
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.className}  antialiased`}
      >
        <Suspense fallback={<Loading />}>
          <WishlistProvider>
            <AuthProvider>
              <CartProvider>
                <NextTopLoader />
                <Toaster position="bottom-right" richColors />
                {children}
              </CartProvider>
            </AuthProvider>
          </WishlistProvider>
        </Suspense>
      </body>
    </html>
  );
}
